import type { CliDiagnosticPayload } from "@/lib/cli-types";

/** Hand-fabricated payloads covering every leaf key in `messages.en.json`. */
export const ALL_MESSAGE_DIAGNOSTICS: CliDiagnosticPayload[] = [
  // app
  {
    severity: "Error",
    message: { key: "app.batch_size_invalid" },
    path: "debug/app.msg",
    line: 1,
    time: 1,
  },
  {
    severity: "Error",
    message: { key: "app.chart_file_not_found" },
    path: "debug/app.msg",
    line: 2,
    time: 2,
  },
  {
    severity: "Error",
    message: { key: "app.config_path_conflict" },
    path: "debug/app.msg",
    line: 3,
    time: 3,
  },
  {
    severity: "Error",
    message: { key: "app.game_directory_not_found" },
    path: "debug/app.msg",
    line: 4,
    time: 4,
  },
  {
    severity: "Error",
    message: { key: "app.input_directory_not_found" },
    path: "debug/app.msg",
    line: 5,
    time: 5,
  },
  {
    severity: "Error",
    message: { key: "app.no_charts_to_export" },
    path: "debug/app.msg",
    line: 6,
    time: 6,
  },
  {
    severity: "Error",
    message: { key: "app.no_export_actions_enabled" },
    path: "debug/app.msg",
    line: 7,
    time: 7,
  },
  {
    severity: "Error",
    message: { key: "app.option_name_required" },
    path: "debug/app.msg",
    line: 8,
    time: 8,
  },
  {
    severity: "Error",
    message: { key: "app.output_directory_not_found" },
    path: "debug/app.msg",
    line: 9,
    time: 9,
  },
  {
    severity: "Error",
    message: { key: "app.unsupported_chart_extension" },
    path: "debug/app.msg",
    line: 10,
    time: 10,
  },

  // cli.msg
  {
    severity: "Information",
    message: { key: "cli.msg.assets_collected", args: { arg0: "assets/db.json" } },
    path: "debug/cli.msg",
    line: 1,
    time: 11,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.audio_exported", args: { arg0: "music/0001.wav" } },
    path: "debug/cli.msg",
    line: 2,
    time: 12,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.built_stage", args: { arg0: "stage/s001.afb" } },
    path: "debug/cli.msg",
    line: 3,
    time: 13,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.chart_written", args: { arg0: "charts/0001_00.c2s" } },
    path: "debug/cli.msg",
    line: 4,
    time: 14,
  },
  {
    severity: "Error",
    message: { key: "cli.msg.command_line_parsing_failed", args: { arg0: "unknown option --foo" } },
    path: "debug/cli.msg",
    line: 5,
    time: 15,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.exported_music", args: { arg0: "music/0001" } },
    path: "debug/cli.msg",
    line: 6,
    time: 16,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.extracted_dds", args: { arg0: "textures/" } },
    path: "debug/cli.msg",
    line: 7,
    time: 17,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.jacket_written", args: { arg0: "jackets/0001.png" } },
    path: "debug/cli.msg",
    line: 8,
    time: 18,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.operation_cancelled" },
    path: "debug/cli.msg",
    line: 9,
    time: 19,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.option_build_complete", args: { arg0: "A001", arg1: "out/A001" } },
    path: "debug/cli.msg",
    line: 10,
    time: 20,
  },
  {
    severity: "Information",
    message: { key: "cli.msg.option_scan_complete", args: { arg0: "3", arg1: "12" } },
    path: "debug/cli.msg",
    line: 11,
    time: 21,
  },

  // diag.c2s
  {
    severity: "Error",
    message: { key: "diag.c2s.invalid_field", args: { arg0: "VERSION" } },
    path: "charts/sample.c2s",
    line: 1,
    time: 22,
  },
  {
    severity: "Error",
    message: { key: "diag.c2s.missing_field", args: { arg0: "RESOLUTION" } },
    path: "charts/sample.c2s",
    line: 2,
    time: 23,
  },
  {
    severity: "Warning",
    message: { key: "diag.c2s.note_type_not_represented", args: { arg0: "AIR-ACTION" } },
    path: "charts/sample.c2s",
    line: 40,
    time: 24,
  },
  {
    severity: "Error",
    message: { key: "diag.c2s.parent_not_resolved", args: { arg0: "HOLD", arg1: "AIR" } },
    path: "charts/sample.c2s",
    line: 88,
    time: 25,
  },
  {
    severity: "Error",
    message: { key: "diag.c2s.resolution_must_be_positive" },
    path: "charts/sample.c2s",
    line: 3,
    time: 26,
  },
  {
    severity: "Warning",
    message: { key: "diag.c2s.unknown_air_color", args: { arg0: "rainbow" } },
    path: "charts/sample.c2s",
    line: 120,
    time: 27,
  },
  {
    severity: "Warning",
    message: { key: "diag.c2s.unknown_ex_effect", args: { arg0: "sparkle" } },
    path: "charts/sample.c2s",
    line: 121,
    time: 28,
  },
  {
    severity: "Error",
    message: { key: "diag.c2s.unsupported_version", args: { arg0: "99.0" } },
    path: "charts/sample.c2s",
    line: 1,
    time: 29,
  },
  {
    severity: "Error",
    message: { key: "diag.c2s.version_line_not_found" },
    path: "charts/sample.c2s",
    line: 1,
    time: 30,
  },

  // diag.error
  {
    severity: "Error",
    message: { key: "diag.error.audio_file_not_found" },
    path: "audio/missing.wav",
    line: 1,
    time: 31,
  },
  {
    severity: "Error",
    message: { key: "diag.error.audio_format_not_supported" },
    path: "audio/bad.mp3",
    line: 1,
    time: 32,
  },
  {
    severity: "Error",
    message: { key: "diag.error.background_file_is_not_set" },
    path: "stage/config.json",
    line: 1,
    time: 33,
  },
  {
    severity: "Error",
    message: { key: "diag.error.background_file_not_found" },
    path: "stage/bg.png",
    line: 1,
    time: 34,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_conversion_unsupported", args: { arg0: "sus → mgxc" } },
    path: "charts/sample.sus",
    line: 1,
    time: 35,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_discovery_array_incomplete" },
    path: "options.json",
    line: 12,
    time: 36,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_discovery_must_be_array" },
    path: "options.json",
    line: 12,
    time: 37,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_discovery_must_be_string_or_array" },
    path: "options.json",
    line: 12,
    time: 38,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_format_brackets_mismatch" },
    path: "options.json",
    line: 12,
    time: 39,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_format_specify_at_least_one" },
    path: "options.json",
    line: 12,
    time: 40,
  },
  {
    severity: "Error",
    message: { key: "diag.error.chart_format_unsupported", args: { arg0: "bms" } },
    path: "options.json",
    line: 12,
    time: 41,
  },
  {
    severity: "Error",
    message: { key: "diag.error.command_failed" },
    path: "debug/command.msg",
    line: 1,
    time: 42,
  },
  {
    severity: "Error",
    message: { key: "diag.error.effect_file_not_found" },
    path: "stage/fx.png",
    line: 1,
    time: 43,
  },
  {
    severity: "Error",
    message: { key: "diag.error.file_ignored_due_to_id_missing" },
    path: "charts/untitled.ugc",
    line: 1,
    time: 44,
  },
  {
    severity: "Error",
    message: { key: "diag.error.file_not_found" },
    path: "missing.bin",
    line: 1,
    time: 45,
  },
  {
    severity: "Error",
    message: { key: "diag.error.invalid_audio" },
    path: "audio/corrupt.wav",
    line: 1,
    time: 46,
  },
  {
    severity: "Error",
    message: { key: "diag.error.invalid_bg_fx_image" },
    path: "stage/fx.bmp",
    line: 1,
    time: 47,
  },
  {
    severity: "Error",
    message: { key: "diag.error.invalid_bg_image" },
    path: "stage/bg.bmp",
    line: 1,
    time: 48,
  },
  {
    severity: "Error",
    message: { key: "diag.error.invalid_header", args: { arg0: "UGC1", arg1: "MGXC" } },
    path: "charts/sample.ugc",
    line: 1,
    time: 49,
  },
  {
    severity: "Error",
    message: { key: "diag.error.invalid_jk_image" },
    path: "jackets/bad.gif",
    line: 1,
    time: 50,
  },
  {
    severity: "Error",
    message: { key: "diag.error.jacket_file_not_found" },
    path: "jackets/missing.png",
    line: 1,
    time: 51,
  },
  {
    severity: "Error",
    message: { key: "diag.error.main_meta_is_null" },
    path: "charts/book/",
    line: 1,
    time: 52,
  },
  {
    severity: "Error",
    message: { key: "diag.error.preview_stop_greater_than_start" },
    path: "charts/sample.ugc",
    line: 8,
    time: 53,
  },
  {
    severity: "Error",
    message: {
      key: "diag.error.size_incompatible",
      args: { arg0: "1024", arg1: "header", arg2: "64" },
    },
    path: "data/chunk.bin",
    line: 1,
    time: 54,
  },
  {
    severity: "Error",
    message: { key: "diag.error.song_id_is_not_set" },
    path: "charts/sample.ugc",
    line: 4,
    time: 55,
  },
  {
    severity: "Error",
    message: { key: "diag.error.stage_background_required" },
    path: "stage/build.json",
    line: 1,
    time: 56,
  },
  {
    severity: "Error",
    message: { key: "diag.error.stage_id_is_not_set" },
    path: "stage/build.json",
    line: 2,
    time: 57,
  },
  {
    severity: "Error",
    message: {
      key: "diag.error.unhandled",
      args: { detail: "NullReferenceException at StageBuilder" },
    },
    path: "debug/unhandled.msg",
    line: 1,
    time: 58,
  },

  // diag.hint
  {
    severity: "Information",
    message: { key: "diag.hint.preview_start_clamped", args: { arg0: "180", arg1: "120" } },
    path: "charts/sample.ugc",
    line: 8,
    time: 59,
  },
  {
    severity: "Information",
    message: { key: "diag.hint.preview_stop_clamped", args: { arg0: "200", arg1: "120" } },
    path: "charts/sample.ugc",
    line: 9,
    time: 60,
  },

  // diag.mg
  {
    severity: "Warning",
    message: { key: "diag.mg.concurrent_ex_effects", args: { arg0: "1024" } },
    path: "charts/sample.ugc",
    line: 64,
    time: 61,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.head_bpm_not_found" },
    path: "charts/sample.ugc",
    line: 1,
    time: 62,
  },
  {
    severity: "Information",
    message: { key: "diag.mg.head_time_signature_event_not_found" },
    path: "charts/sample.ugc",
    line: 1,
    time: 63,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.invalid_joint_type_note", args: { arg0: "SLIDE" } },
    path: "charts/sample.ugc",
    line: 90,
    time: 64,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.length_smaller_than_unit", args: { arg0: "1", arg1: "384" } },
    path: "charts/sample.ugc",
    line: 91,
    time: 65,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.main_timeline_not_found", args: { arg0: "til1" } },
    path: "charts/sample.ugc",
    line: 20,
    time: 66,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.meta_argument_count_min_one", args: { arg0: "#meta bpm" } },
    path: "charts/sample.ugc",
    line: 5,
    time: 67,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.meta_first_argument_must_int" },
    path: "charts/sample.ugc",
    line: 6,
    time: 68,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.meta_invalid_date" },
    path: "charts/sample.ugc",
    line: 7,
    time: 69,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.meta_unknown_tag", args: { arg0: "foo" } },
    path: "charts/sample.ugc",
    line: 8,
    time: 70,
  },
  {
    severity: "Information",
    message: { key: "diag.mg.no_sortname_provided" },
    path: "charts/sample.ugc",
    line: 3,
    time: 71,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.note_overlapped_in_different_til" },
    path: "charts/sample.ugc",
    line: 110,
    time: 72,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.overlapping_air_parent_slide" },
    path: "charts/sample.ugc",
    line: 140,
    time: 73,
  },
  {
    severity: "Warning",
    message: {
      key: "diag.mg.string_id_not_found",
      args: { arg0: "STR_0001", arg1: "assets/strings.json" },
    },
    path: "charts/sample.ugc",
    line: 9,
    time: 74,
  },
  {
    severity: "Information",
    message: { key: "diag.mg.unrecognized_meta", args: { arg0: "custom", arg1: "value" } },
    path: "charts/sample.ugc",
    line: 10,
    time: 75,
  },
  {
    severity: "Warning",
    message: { key: "diag.mg.unrecognized_note", args: { arg0: "Z" } },
    path: "charts/sample.ugc",
    line: 150,
    time: 76,
  },

  // diag.mgcrit
  {
    severity: "Error",
    message: { key: "diag.mgcrit.air_parent_null" },
    path: "charts/sample.ugc",
    line: 160,
    time: 77,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.air_slide_parent_null" },
    path: "charts/sample.ugc",
    line: 161,
    time: 78,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.hold_has_no_tail" },
    path: "charts/sample.ugc",
    line: 162,
    time: 79,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.invalid_air_parent" },
    path: "charts/sample.ugc",
    line: 163,
    time: 80,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.invalid_airslide_parent" },
    path: "charts/sample.ugc",
    line: 164,
    time: 81,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.pairing_notes_incompatible" },
    path: "charts/sample.ugc",
    line: 165,
    time: 82,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.soflanarea_has_no_tail" },
    path: "charts/sample.ugc",
    line: 166,
    time: 83,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.unrecognized_data_type", args: { arg0: "42" } },
    path: "charts/sample.ugc",
    line: 167,
    time: 84,
  },
  {
    severity: "Error",
    message: { key: "diag.mgcrit.unrecognized_event", args: { arg0: "UNKNOWN" } },
    path: "charts/sample.ugc",
    line: 168,
    time: 85,
  },

  // diag.sus
  {
    severity: "Warning",
    message: { key: "diag.sus.air_hold_ignored" },
    path: "charts/sample.sus",
    line: 40,
    time: 86,
  },
  {
    severity: "Warning",
    message: { key: "diag.sus.air_hold_joint_ignored" },
    path: "charts/sample.sus",
    line: 41,
    time: 87,
  },
  {
    severity: "Warning",
    message: { key: "diag.sus.air_note_ignored" },
    path: "charts/sample.sus",
    line: 42,
    time: 88,
  },
  {
    severity: "Warning",
    message: { key: "diag.sus.bpm_definition_not_found", args: { arg0: "A" } },
    path: "charts/sample.sus",
    line: 10,
    time: 89,
  },
  {
    severity: "Warning",
    message: { key: "diag.sus.hold_joint_ignored" },
    path: "charts/sample.sus",
    line: 50,
    time: 90,
  },
  {
    severity: "Warning",
    message: { key: "diag.sus.malformed_line", args: { arg0: "#00008:zz" } },
    path: "charts/sample.sus",
    line: 60,
    time: 91,
  },
  {
    severity: "Warning",
    message: { key: "diag.sus.slide_joint_ignored" },
    path: "charts/sample.sus",
    line: 70,
    time: 92,
  },
  {
    severity: "Information",
    message: { key: "diag.sus.unsupported_air_hold_point_type", args: { arg0: "9" } },
    path: "charts/sample.sus",
    line: 80,
    time: 93,
  },
  {
    severity: "Information",
    message: { key: "diag.sus.unsupported_hold_point_type", args: { arg0: "9" } },
    path: "charts/sample.sus",
    line: 81,
    time: 94,
  },
  {
    severity: "Information",
    message: { key: "diag.sus.unsupported_slide_point_type", args: { arg0: "9" } },
    path: "charts/sample.sus",
    line: 82,
    time: 95,
  },
  {
    severity: "Information",
    message: { key: "diag.sus.unsupported_tap_point_type", args: { arg0: "9" } },
    path: "charts/sample.sus",
    line: 83,
    time: 96,
  },

  // diag.warn
  {
    severity: "Warning",
    message: { key: "diag.warn.config_invalid", args: { arg0: "Unexpected end of JSON" } },
    path: "options.json",
    line: 1,
    time: 97,
  },
  {
    severity: "Warning",
    message: { key: "diag.warn.duplicate_id_and_difficulty" },
    path: "charts/dup.ugc",
    line: 1,
    time: 98,
  },
  {
    severity: "Warning",
    message: { key: "diag.warn.more_than_one_chart_marked_main" },
    path: "charts/book/",
    line: 1,
    time: 99,
  },
  {
    severity: "Warning",
    message: { key: "diag.warn.no_chart_marked_main" },
    path: "charts/book/",
    line: 1,
    time: 100,
  },
  {
    severity: "Warning",
    message: { key: "diag.warn.preview_later_than_120" },
    path: "charts/sample.ugc",
    line: 8,
    time: 101,
  },
  {
    severity: "Warning",
    message: { key: "diag.warn.stage_already_exists", args: { arg0: "Default", arg1: "1" } },
    path: "stage/s001",
    line: 1,
    time: 102,
  },
  {
    severity: "Warning",
    message: { key: "diag.warn.we_chart_must_be_unique_id" },
    path: "charts/we.ugc",
    line: 4,
    time: 103,
  },
];
